export async function query () {
  let menu = [
    {
      id: 1,
      name: '全局监测',
      route: '/summary',
    },
    {
      id: 2,
      name: '视频配置',
      route: '/video-settings',
    },
    {
      id: 4,
      name: '参数配置',
      route: '/global-settings',
    },
    {
      id: 3,
      name: '微信配置',
      route: '/wechat-public-settings',
    },
    {
      id: 5,
      name: '接口配置',
      route: '/interface-settings',
    },
    // {
    //   id: 101,
    //   bpid: 1,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/spu/:id',
    // },
    // {
    //   id: 6,
    //   bpid: 0,
    //   name: '分类标签',
    // },
    // {
    //   id: 61,
    //   bpid: 6,
    //   mpid: 6,
    //   name: '行业分类',
    //   route: '/tag/industry',
    // },
    // {
    //   id: 62,
    //   bpid: 6,
    //   mpid: 6,
    //   name: '标准分类',
    //   route: '/tag/standard',
    // },
    // {
    //   id: 2,
    //   name: 'ITEM - 标准化',
    //   route: '/item-spu',
    // },
    // // {
    // //   id: 201,
    // //   name: 'Item - 标准化 V2',
    // //   route: '/item/spu',
    // // },
    // {
    //   id: 21,
    //   bpid: 2,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/item-spu/:id',
    // },
    // {
    //   id: 4,
    //   name: 'CFDA - 标准化',
    //   route: '/cfda',
    // },
    // {
    //   id: 41,
    //   bpid: 4,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/cfda-spu/:id',
    // },
    // {
    //   id: 3,
    //   bpid: 0,
    //   name: '标准化数据管理',
    // },
    // {
    //   id: 31,
    //   bpid: 3,
    //   mpid: 3,
    //   name: '通用名',
    //   route: '/std/common-name',
    // },
    // {
    //   id: 311,
    //   bpid: 31,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/std/common-name/:id',
    // },
    // {
    //   id: 32,
    //   bpid: 3,
    //   mpid: 3,
    //   name: '型号',
    //   route: '/std/model',
    // },
    // {
    //   id: 33,
    //   bpid: 3,
    //   mpid: 3,
    //   name: '品牌',
    //   route: '/std/brand',
    // },
    // {
    //   id: 34,
    //   bpid: 3,
    //   mpid: 3,
    //   name: '机构',
    //   route: '/std/organization',
    // },
    // {
    //   id: 35,
    //   bpid: 3,
    //   mpid: 3,
    //   name: '科室',
    //   route: '/std/department',
    // },
    // {
    //   id: 5,
    //   bpid: 0,
    //   name: '规则管理',
    // },
    // {
    //   id: 51,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '名称 - 通用名',
    //   route: '/common-name',
    // },
    // {
    //   id: 52,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '型号 - 标准化型号',
    //   route: '/model',
    // },
    // {
    //   id: 53,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '品牌 - 标准化品牌',
    //   route: '/brand',
    // },
    // {
    //   id: 54,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '机构 - 标准化品牌',
    //   route: '/organization/brand',
    // },
    // {
    //   id: 55,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '机构 - 标准化机构',
    //   route: '/organization/org',
    // },
    // {
    //   id: 57,
    //   bpid: 5,
    //   mpid: 5,
    //   name: '科室 - 标准化科室',
    //   route: '/department',
    // },
    // {
    //   id: 2048,
    //   bpid: 0,
    //   name: '系统配置',
    //   roles: ['ADMINISTRATOR'],
    // },
    // {
    //   id: 20481,
    //   bpid: 2048,
    //   mpid: 2048,
    //   name: '报表配置',
    //   route: '/setting/report',
    //   roles: ['ADMINISTRATOR'],
    // },
    // {
    //   id: 204811,
    //   bpid: 20481,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/setting/report/:id',
    // },
    // {
    //   id: 20482,
    //   bpid: 2048,
    //   mpid: 2048,
    //   name: '权限管理',
    //   route: '/setting/acl',
    //   roles: ['ADMINISTRATOR'],
    // },
    // {
    //   id: 204821,
    //   bpid: 20482,
    //   mpid: -1,
    //   name: ':id',
    //   route: '/setting/acl/:id',
    // },
  ]
  return menu
}
